// <auto-generated />
using System;
using HinweigeberRestApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HinweigeberRestApi.Migrations
{
    [DbContext(typeof(HinweisDbContext))]
    [Migration("20231207113633_newmig22")]
    partial class newmig22
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HinweigeberRestApi.Data.Massnahme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Massnahmes");
                });

            modelBuilder.Entity("HinweigeberRestApi.Data.Meldung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<bool>("isFinished")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Meldungs");
                });

            modelBuilder.Entity("HinweigeberRestApi.Data.Weitereinfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeldungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeldungId");

                    b.ToTable("Weitereinfo");
                });

            modelBuilder.Entity("MassnahmeMeldung", b =>
                {
                    b.Property<int>("MassnahmenId")
                        .HasColumnType("int");

                    b.Property<int>("MeldungenId")
                        .HasColumnType("int");

                    b.HasKey("MassnahmenId", "MeldungenId");

                    b.HasIndex("MeldungenId");

                    b.ToTable("MassnahmeMeldung");
                });

            modelBuilder.Entity("HinweigeberRestApi.Data.Weitereinfo", b =>
                {
                    b.HasOne("HinweigeberRestApi.Data.Meldung", "Meldung")
                        .WithMany("Weitereinfos")
                        .HasForeignKey("MeldungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meldung");
                });

            modelBuilder.Entity("MassnahmeMeldung", b =>
                {
                    b.HasOne("HinweigeberRestApi.Data.Massnahme", null)
                        .WithMany()
                        .HasForeignKey("MassnahmenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HinweigeberRestApi.Data.Meldung", null)
                        .WithMany()
                        .HasForeignKey("MeldungenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HinweigeberRestApi.Data.Meldung", b =>
                {
                    b.Navigation("Weitereinfos");
                });
#pragma warning restore 612, 618
        }
    }
}
